import {
  CiIceCream,
  CiLemon,
  CiLollipop,
  CiPizza,
  CiUmbrella,
  CiStar,
  CiRainbow,
  CiMedal,
  CiFries,
  CiHotdog,
  CiMedicalCross,
  CiPaperplane,
  CiPenpot,
  CiSatellite1,
  CiShirt,
} from 'react-icons/ci'

export const categories = [
  { name: '개밍순', icon: <CiIceCream /> },
  { name: '루퐁이네 ', icon: <CiLemon /> },
  { name: '사둥이네TV', icon: <CiLollipop /> },
  { name: '소녀의행성', icon: <CiPizza /> },
  { name: '뮤직 메이트', icon: <CiUmbrella /> },
  { name: '하오TV', icon: <CiStar /> },
  { name: '보통견주', icon: <CiRainbow /> },
  { name: '시바견 미쓰리 ', icon: <CiMedal /> },
  { name: '키쉬의 브이로그', icon: <CiFries /> },
  { name: '뚜비TV', icon: <CiHotdog /> },
  { name: '토토튜브', icon: <CiMedicalCross /> },
  { name: '곰이탱이여우', icon: <CiPaperplane /> },
  { name: '명랑한 봄달래', icon: <CiPenpot /> },
  { name: '포메라니안 레페', icon: <CiSatellite1 /> },
  { name: '사모예드 티코', icon: <CiShirt /> },
]
